/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "teal-accent": "#14B8A6",
        "electric-cyan": "#14B8A6",
        "amber-gold": "#14B8A6",
        "slate-dark": "rgba(26, 31, 46, 0.65)",
        "deep-navy": "#0a0a0a",
        "on-error": "#690005",
        surface: "rgba(19, 19, 19, 0.7)",
        "on-tertiary-container": "#006274",
        "inverse-surface": "#e5e2e1",
        "surface-base": "#0a0a0a",
        background: "#0a0a0a",
        "surface-container-lowest": "rgba(14, 14, 14, 0.6)",
        "surface-container-low": "rgba(28, 27, 27, 0.7)",
        "secondary-container": "#03c6b2",
        "tertiary-fixed": "#acedff",
        "primary-container": "#6ee7b7",
        "text-muted": "#A3A3A3",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005047",
        "primary-fixed-dim": "#62dcad",
        "surface-container-highest": "rgba(53, 53, 52, 0.85)",
        "surface-tint": "#62dcad",
        "border-glass": "rgba(255, 255, 255, 0.08)",
        error: "#ffb4ab",
        "on-primary-container": "#006649",
        secondary: "#44e2cd",
        "on-secondary-fixed": "#00201c",
        "on-surface": "#e5e2e1",
        "on-primary": "#003827",
        "secondary-fixed-dim": "#3cddc7",
        "status-success": "#10B981",
        "secondary-fixed": "#62fae3",
        "text-primary": "#FFFFFF",
        "primary-fixed": "#80f9c8",
        "on-tertiary": "#003640",
        "surface-dim": "rgba(19, 19, 19, 0.6)",
        "on-background": "#e5e2e1",
        primary: "#aaffd8",
        "on-surface-variant": "#bccac1",
        "on-primary-fixed-variant": "#00513a",
        "surface-elevated": "rgba(24, 24, 24, 0.75)",
        "status-error": "#EF4444",
        "on-secondary": "#003731",
        "tertiary-fixed-dim": "#4cd7f6",
        "error-container": "#93000a",
        "on-primary-fixed": "#002115",
        "on-secondary-container": "#004d44",
        "outline-variant": "#3d4a43",
        tertiary: "#cef4ff",
        "on-tertiary-fixed": "#001f26",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#006c4e",
        outline: "#86948c",
        "on-tertiary-fixed-variant": "#004e5c",
        "tertiary-container": "#63e1ff",
        "surface-bright": "rgba(58, 57, 57, 0.85)",
        "surface-variant": "rgba(53, 53, 52, 0.8)",
        "surface-container-high": "rgba(42, 42, 42, 0.8)",
        "surface-container": "rgba(32, 31, 31, 0.75)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "section-gap": "80px",
        unit: "8px",
        "container-margin": "24px",
      },
      fontFamily: {
        sora: ["Sora", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-xl": ["Sora", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "button-text": ["Inter", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "label-mono": ["IBM Plex Mono", "monospace"],
        code: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "button-text": ["14px", { lineHeight: "1.0", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-mono": ["13px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
