import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { router, protectedProcedure, editorProcedure } from "../_core/trpc";
import * as db from "../db";
import {
  generateOWASPRequirements,
  generatePCIDSSRequirements,
  generateGDPRRequirements,
  type CollectionData,
} from "../utils/scanning";
import { generateReport } from "../engines/complianceEngine";
import { toNumber } from "../utils/decimal";
import PDFDocument from "pdfkit";
import { requireCollectionAccess } from "../services/tenantAccess";
import { logger } from "../_core/logger";

/**
 * Shape of a single compliance requirement persisted in
 * complianceReports.requirementsData. Generated by
 * `generatePCIDSSRequirements` / `generateOWASPRequirements` and
 * consumed by the dashboard. The column is typed `json` in MySQL so
 * Drizzle returns it as `unknown` — we narrow it here.
 */
const complianceRequirementSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string(),
  status: z.enum(["met", "not_met", "manual_review"]),
});
export type ComplianceRequirement = z.infer<typeof complianceRequirementSchema>;
const complianceRequirementsSchema = z.array(complianceRequirementSchema);

function parseRequirements(raw: unknown): ComplianceRequirement[] {
  const result = complianceRequirementsSchema.safeParse(raw);
  return result.success ? result.data : [];
}

export const complianceRouter = router({
  generateReport: editorProcedure
    .input(
      z.object({
        collectionId: z.string(),
        reportType: z.enum(["pci_dss", "owasp", "owasp_llm", "dpdp", "gdpr"]).default("pci_dss"),
      }),
    )
    .mutation(async ({ input, ctx }) => {
      const { collection } = await requireCollectionAccess(
        input.collectionId,
        ctx.user.id,
        "collections",
        "write",
        ctx.user.name,
      );

      // Get findings for this collection to power the compliance engine
      const scans = await db.getScansByCollectionId(input.collectionId);
      const allFindings: Array<{
        title?: string;
        description?: string;
        severity?: string;
        category?: string;
        cweId?: string;
      }> = [];

      for (const scan of scans) {
        const findings = await db.getFindingsByScanId(scan.id);
        for (const f of findings) {
          allFindings.push({
            title: f.title ?? undefined,
            description: f.description ?? undefined,
            severity: f.severity ?? undefined,
            category: f.category ?? undefined,
            cweId: f.cweId ?? undefined,
          });
        }
      }

      let reportResult: {
        requirements: Array<{
          id: string;
          title: string;
          description: string;
          status: "met" | "not_met" | "manual_review";
        }>;
        metCount: number;
        notMetCount: number;
        manualCount: number;
        score: number;
      };

      if (input.reportType === "owasp") {
        const requirements = generateOWASPRequirements(collection.data as CollectionData);
        const met = requirements.filter((r: any) => r.status === "met").length;
        reportResult = {
          requirements: requirements as any,
          metCount: met,
          notMetCount:
            requirements.length -
            met -
            requirements.filter((r: any) => r.status === "manual_review").length,
          manualCount: requirements.filter((r: any) => r.status === "manual_review").length,
          score: requirements.length > 0 ? (met / requirements.length) * 100 : 0,
        };
      } else if (input.reportType === "pci_dss") {
        const requirements = generatePCIDSSRequirements(collection.data as CollectionData);
        const met = requirements.filter((r: any) => r.status === "met").length;
        reportResult = {
          requirements: requirements as any,
          metCount: met,
          notMetCount:
            requirements.length -
            met -
            requirements.filter((r: any) => r.status === "manual_review").length,
          manualCount: requirements.filter((r: any) => r.status === "manual_review").length,
          score: requirements.length > 0 ? (met / requirements.length) * 100 : 0,
        };
      } else if (input.reportType === "gdpr") {
        const requirements = generateGDPRRequirements(collection.data as CollectionData);
        const met = requirements.filter((r: any) => r.status === "met").length;
        reportResult = {
          requirements: requirements as any,
          metCount: met,
          notMetCount:
            requirements.length -
            met -
            requirements.filter((r: any) => r.status === "manual_review").length,
          manualCount: requirements.filter((r: any) => r.status === "manual_review").length,
          score: requirements.length > 0 ? (met / requirements.length) * 100 : 0,
        };
      } else {
        // owasp_llm or dpdp — use the compliance engine
        const result = generateReport(allFindings as any, [input.reportType]);
        reportResult = result as any;
      }

      const report = await db.createComplianceReport(
        ctx.user.id,
        input.collectionId,
        input.reportType as any,
        reportResult.score,
        reportResult.requirements.length,
        reportResult.metCount,
        reportResult.requirements,
      );

      try {
        await db.updateOnboardingStep(ctx.user.id, "setupCompliance");
      } catch (err) {
        logger.warn({ err }, "[Compliance] onboarding step update skipped");
      }

      return {
        reportId: report.id,
        complianceScore: Math.round(reportResult.score),
        totalRequirements: reportResult.requirements.length,
        metRequirements: reportResult.metCount,
        manualRequirements: reportResult.manualCount,
        notMetRequirements: reportResult.notMetCount,
        requirements: reportResult.requirements,
      };
    }),

  listReports: protectedProcedure
    .input(
      z.object({
        collectionId: z.string(),
        page: z.number().int().min(1).default(1),
        pageSize: z.number().int().min(1).max(100).default(20),
      }),
    )
    .query(async ({ input, ctx }) => {
      await requireCollectionAccess(
        input.collectionId,
        ctx.user.id,
        "collections",
        "read",
        ctx.user.name,
      );

      const reports = await db.getComplianceReportsByCollectionId(input.collectionId);
      const page = input.page ?? 1;
      const pageSize = input.pageSize ?? 20;
      const total = reports.length;
      const paginated = reports.slice((page - 1) * pageSize, page * pageSize);

      return {
        reports: paginated.map((r: any) => ({
          id: r.id,
          reportType: r.reportType,
          complianceScore: toNumber(r.complianceScore),
          totalRequirements: r.totalRequirements,
          metRequirements: r.metRequirements,
          createdAt: r.createdAt,
        })),
        total,
        page,
        pageSize,
        totalPages: Math.ceil(total / pageSize),
      };
    }),

  /**
   * Latest compliance score per report type for the signed-in user. Drives
   * the IDE panel's compliance tiles; returns nulls rather than erroring when
   * a framework has never been scanned, so the client can render an empty
   * state without special-casing.
   */
  latestScores: protectedProcedure.query(async ({ ctx }) => {
    const latest = await db.getLatestComplianceScoresForUser(ctx.user.id);
    // Keys must match the report_type enum values ("pci_dss", not "pci").
    return {
      owasp: latest["owasp"] ?? null,
      pci: latest["pci_dss"] ?? null,
    };
  }),

  getReport: protectedProcedure
    .input(z.object({ reportId: z.string() }))
    .query(async ({ input, ctx }) => {
      const report = await db.getComplianceReportById(input.reportId);
      if (!report || report.userId !== ctx.user.id) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Report not found or access denied",
        });
      }

      const requirements = parseRequirements(report.requirementsData);
      const manualRequirements = requirements.filter((r) => r.status === "manual_review").length;
      const notMetRequirements = requirements.filter((r) => r.status === "not_met").length;

      return {
        id: report.id,
        reportType: report.reportType,
        complianceScore: toNumber(report.complianceScore),
        totalRequirements: report.totalRequirements,
        metRequirements: report.metRequirements,
        manualRequirements,
        notMetRequirements,
        requirements: report.requirementsData,
        createdAt: report.createdAt,
      };
    }),

  exportReport: protectedProcedure
    .input(z.object({ reportId: z.string() }))
    .mutation(async ({ input, ctx }) => {
      const report = await db.getComplianceReportById(input.reportId);
      if (!report || report.userId !== ctx.user.id) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Report not found or access denied",
        });
      }

      const collection = await db.getCollectionById(report.collectionId);
      const requirements = parseRequirements(report.requirementsData);
      const metCount = requirements.filter((r) => r.status === "met").length;
      const manualCount = requirements.filter((r) => r.status === "manual_review").length;
      const notMetCount = requirements.filter((r) => r.status === "not_met").length;

      // Generate PDF using PDFKit
      const pdfBuffer = await generateCompliancePDF({
        report,
        collectionName: collection?.name || "Unknown Collection",
        requirements,
        metCount,
        manualCount,
        notMetCount,
      });

      return {
        reportId: report.id,
        reportType: report.reportType,
        complianceScore: toNumber(report.complianceScore),
        pdfBase64: pdfBuffer.toString("base64"),
        filename: `Rakshex-compliance-report-${new Date().toISOString().split("T")[0]}.pdf`,
        exportDate: new Date().toISOString(),
      };
    }),
});

// Helper function to generate PDF
async function generateCompliancePDF(data: {
  report: any;
  collectionName: string;
  requirements: any[];
  metCount: number;
  manualCount: number;
  notMetCount: number;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const { report, collectionName, requirements, metCount, manualCount, notMetCount } = data;
    const REPORT_TYPE_LABELS: Record<string, string> = {
      pci_dss: "PCI DSS v4.0.1",
      owasp: "OWASP API Top 10",
      owasp_llm: "OWASP LLM Top 10",
      dpdp: "DPDP Act",
      gdpr: "GDPR",
      custom: "Custom",
    };
    const reportType = REPORT_TYPE_LABELS[report.reportType as string] ?? String(report.reportType);
    const score = toNumber(report.complianceScore);

    // Page 1: Header and Executive Summary
    doc.fontSize(24).font("Helvetica-Bold").text("Rakshex Compliance Report", 50, 50);
    doc.fontSize(14).font("Helvetica").text(`${reportType} Security Assessment`, 50, 80);
    doc.fontSize(12).text(`Collection: ${collectionName}`, 50, 105);
    doc.fontSize(12).text(`Generated: ${new Date(report.createdAt).toLocaleDateString()}`, 50, 125);
    doc.fontSize(10).text(`Report ID: ${report.id}`, 50, 145);

    doc.moveDown(2);

    // Executive Summary Box
    doc.rect(50, doc.y, 500, 120).stroke("#2563eb");
    doc
      .fontSize(16)
      .font("Helvetica-Bold")
      .text("Executive Summary", 60, doc.y + 10);
    doc.moveDown(0.5);

    doc.fontSize(14).font("Helvetica");
    doc.text(`Overall Compliance Score: ${score.toFixed(1)}%`, 60);
    doc.moveDown(0.5);

    doc.fontSize(12);
    doc.text(`• Total Requirements: ${report.totalRequirements}`, 60);
    doc.text(`• Requirements Met: ${metCount}`, 60);
    doc.text(`• Manual Review Needed: ${manualCount}`, 60);
    doc.text(`• Not Met: ${notMetCount}`, 60);

    // Page 2: Compliance Score Visualization
    doc.addPage();
    doc.fontSize(20).font("Helvetica-Bold").text("Compliance Breakdown", 50, 50);
    doc.moveDown();

    // Simple bar chart
    const chartY = doc.y;
    const barWidth = 400;
    const barHeight = 25;

    // Met bar (green)
    if (metCount > 0) {
      const metWidth = (metCount / report.totalRequirements) * barWidth;
      doc.rect(50, chartY, metWidth, barHeight).fill("#22c55e");
      doc
        .fillColor("white")
        .fontSize(12)
        .text(`Met: ${metCount}`, 55, chartY + 5);
    }

    // Manual review bar (yellow)
    if (manualCount > 0) {
      const manualWidth = (manualCount / report.totalRequirements) * barWidth;
      const manualX = 50 + (metCount / report.totalRequirements) * barWidth;
      doc.rect(manualX, chartY, manualWidth, barHeight).fill("#eab308");
      doc
        .fillColor("black")
        .fontSize(12)
        .text(`Review: ${manualCount}`, manualX + 5, chartY + 5);
    }

    // Not met bar (red)
    if (notMetCount > 0) {
      const notMetWidth = (notMetCount / report.totalRequirements) * barWidth;
      const notMetX = 50 + ((metCount + manualCount) / report.totalRequirements) * barWidth;
      doc.rect(notMetX, chartY, notMetWidth, barHeight).fill("#ef4444");
      doc
        .fillColor("white")
        .fontSize(12)
        .text(`Not Met: ${notMetCount}`, notMetX + 5, chartY + 5);
    }

    doc.fillColor("black");
    doc.moveDown(3);

    // Requirements Detail Pages
    doc.addPage();
    doc.fontSize(20).font("Helvetica-Bold").text("Requirements Detail", 50, 50);
    doc.moveDown();

    let currentY = doc.y;

    for (const req of requirements || []) {
      // Check if we need a new page
      if (currentY > 700) {
        doc.addPage();
        currentY = 50;
      }

      const statusIcon = req.status === "met" ? "✓" : req.status === "manual_review" ? "?" : "✗";
      const statusColor =
        req.status === "met" ? "#22c55e" : req.status === "manual_review" ? "#eab308" : "#ef4444";
      const statusText =
        req.status === "met" ? "Met" : req.status === "manual_review" ? "Manual Review" : "Not Met";

      doc.fontSize(12).font("Helvetica-Bold").text(`[${req.id}] ${req.title}`, 50, currentY);
      currentY += 20;

      doc.fontSize(10).font("Helvetica").fillColor(statusColor);
      doc.text(`${statusIcon} ${statusText}`, 50, currentY);
      doc.fillColor("black");
      currentY += 15;

      if (req.description) {
        doc.fontSize(10).text(req.description, 50, currentY, { width: 500, align: "left" });
        currentY += 30;
      }

      currentY += 15; // Spacing between requirements
    }

    // Final Page: Footer
    doc.addPage();
    doc.fontSize(14).font("Helvetica-Bold").text("Report Information", 50, 50);
    doc.moveDown();
    doc.fontSize(12).font("Helvetica");
    doc.text(`Report ID: ${report.id}`, 50);
    doc.text(`Generated: ${new Date().toISOString()}`, 50);
    doc.text(`Report Type: ${reportType}`, 50);
    doc.moveDown();
    doc.fontSize(10).text("This report was generated by Rakshex Security Platform.", 50);
    doc.text("For questions or support, contact support@rakshex.in", 50);

    doc.end();
  });
}
